Create DB if doesn't exist

diff --git a/services/teslamate/run b/services/teslamate/run
--- a/services/teslamate/run
+++ b/services/teslamate/run
@@ -41,8 +41,8 @@ ingress_entry=$(curl -X GET \
 export URL_PATH=$ingress_entry
 
 export DATABASE_HOST DATABASE_NAME DATABASE_PASS DATABASE_PORT DATABASE_USER \
-    DISABLE_MQTT MQTT_HOST MQTT_NAMESPACE MQTT_PASSWORD MQTT_TLS_ACCEPT_INVALID_CERTS \
-    MQTT_TLS MQTT_USERNAME IMPORT_DIR PORT TZ DEFAULT_GEOFENCE ENCRYPTION_KEY URL_PATH
+  DISABLE_MQTT MQTT_HOST MQTT_NAMESPACE MQTT_PASSWORD MQTT_TLS_ACCEPT_INVALID_CERTS \
+  MQTT_TLS MQTT_USERNAME IMPORT_DIR PORT TZ DEFAULT_GEOFENCE ENCRYPTION_KEY URL_PATH
 
 # Import dashboards
 if bashio::config.true 'grafana_import_dashboards'; then
@@ -50,15 +50,30 @@ if bashio::config.true 'grafana_import_dashboards'; then
 fi
 
 # Create the PostgreSQL database if it doesn't exist
-if ! pg_isready -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d "$DATABASE_NAME"; then
-    bashio::log.info "Creating database $DATABASE_NAME on $DATABASE_HOST"
-    psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -c "CREATE DATABASE $DATABASE_NAME"
+if pg_isready -h "$DATABASE_HOST" -p "$DATABASE_PORT" > /dev/null 2>&1; then
+  bashio::log.info "Creating database $DATABASE_NAME on $DATABASE_HOST"
+
+  res=$(PGPASSWORD="$DATABASE_PASS" psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" postgres -c "CREATE DATABASE $DATABASE_NAME" 2>&1) || true
+  case "$res" in
+    "CREATE DATABASE")
+      bashio::log.info "Database $DATABASE_NAME created"
+      ;;
+    *"already exists"*)
+      bashio::log.info "Database $DATABASE_NAME already exists"
+      ;;
+    *)
+      bashio::log.error "Failed to create database $DATABASE_NAME: $res"
+      exit 1
+      ;;
+  esac
+else
+  bashio::log.error "PostgreSQL is not ready"
+  exit 1
 fi
 
-# https://developers.home-assistant.io/blog/2023/04/13/new_limits_for_add_ons/
 ulimit -n 1048576
 
 bashio::log.info "Starting TeslaMate"
 
 cd /opt/app
-exec bin/teslamate start
+exec $(/usr/bin/env sh) /entrypoint.sh bin/teslamate start
